const gridData = [
  ["1","31","input","2","input","3","input","input","4"],
  ["input","input","input","input","input","input","input","input","input"],
  ["input","5","input","input","input","input","input","6","input"],
  ["input","7","input","input","input","input","input","8","input"],
  ["9","input","10","input","input","11","input","input","input"],
  ["input","input","input","11","input","12","input","input","input"],
  ["13","input","input","input","input","input","input","14","input"],
  ["input","input","input","input","input","15","input","input","input"],
  ["30","16","input","17","input","input","18","input","19"],
  ["input","input","input","input","input","20","input","input","input"],
  ["21","input","input","22","input","input","23","input","input"],
  ["input","input","input","24","input","input","input","input","24"],
  ["input","input","25","input","input","26","27","input","input"],
  ["28","input","input","input","29","input","input","input","input"]
];

const clues = {
  "1": {"downright":"BFF d'Enkidou"},
  "31": {"rightdown":"Rena Rouge"},
  "2": {"right":"Sous-pref du 57 \r ","down":"30 "},
  "3": {"rightdown":"Garo \r ","down":"Délice de pollen "},
  "4": {"down":"Banger de Ateez "},
  "5": {"right":"Toyota "},
  "6": {"up":"Pro "},
  "7": {"right":"Stop \r ","down":"Belle Solis"},
  "8": {"down":"Ile française "},
  "9": {"up":" 💅 \r","downright":"Mahal ? "},
  "10": {"right":"Devienna fou \r ","down":"Fun infini "},
  "11": {"down":"Hormone de l'ovulation "},
  "12": {"right":"Fois en español "},
  "13": {"right":"Cétacé choupi \r","down":"Légende"},
  "14": {"down":"👂 in english "},
  "15": {"right":"Elui ou Salamé "},
  "30": {"downright":"Rappeur goofy "},
  "16": {"down":"Lisières "},
  "17": {"right":"Lettre grecque "},
  "18": {"down":"Question de kikou "},
  "19": {"down":"Saucisse d'Alsace "},
  "20": {"right":"Ile croate \r", "down":"Suffixe "},
  "21": {"right":"Parti de nazis \r", "downright":"Bois "},
  "22": {"right":"Frère de Swan The Voice"},
  "23": {"down":"TER sudiste"},
  "24": {"right":"Schyuler sister\r", "down":"Premier "},
  "25": {"right":"Usages"},
  "26": {"down":"Licorne"},
  "27": {"right":"Occitan pour les intimes"},
  "28": {"up":"Super mention \r ","right":"Capri ?"},
  "29": {"right":"Royaume de Gilga"}
};