// clues.js
// fleches : → ↑ ← ↓ ▲ ▼ ◀ ▶
const clues = {
  "1": { downright: "Chanteur de Cosmo", rightdown: "Fromage  \r -------------" },
  "2": { down: "Ancienne superette" },
  "3": { rightdown: "Pierre précieuse au UK", down: "All clear  \r -------------" },
  "4": { rightdown: "C'est la faute à ..." },
  "5": { rightdown: "Monnaie à Singaour" },
  "6": { down: "Terre natale de la K-POP" },
  "7": { right: "Modèle de Lambo\r -------------", downright: "Ni plante ni champi" },
  "8": { right: "Banque" },
  "9": { right: "Opticien\r -------------", down:"Membre des 1D" },
  "10": { right: "Album de youtubeur\r -------------", downright:"Presque frère"},
  "11": { right: "Grand perroquet\r -------------", down:"Donnèrent"},
  "12": { right: "Métal\r -------------", down:"Pays de Tegucigalpa" },
  "13": { downright: "Departe -ment bordelais" },
  "14": { right: "Ville du Var\r -------------",down:"Editeur de LOL" },
  "15": { down: "Ensemble des entiers relatifs" },
  "16": { down: "Dément" },
  "17": { right: "Einst...?\r -------------",downright: "Coudra" },
  "18": { down: "Paradis"},
  "19": { right: "Zinc\r -------------", down:"... et à travers" },
  "20": { down: "A toi" },
  "21": { right: "Petit studio\r -------------", down:"Bonjour de la street" },
  "22": { down: "Type de crayon" },
  "23": { right: "Black"},
  "24": { down: "Petit élu" },
  "25": { right: "Tanières" },
  "26": { up:"Cri de surprise\r -------------",rightenbas: "Chef" },
  "27": { right: "Explosif" },
};